branches:
  only:
    - master
language: objective-c
osx_image: xcode6.4
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
  matrix:
    - TEST_TYPE=ios
    - TEST_TYPE=osx
    - TEST_TYPE=deployment
    - TEST_TYPE=starters
    - TEST_TYPE=podspecs
install:
  - bundle install
script:
  - bundle exec rake test:$TEST_TYPE
after_success:
- | 
  if [ "$TEST_TYPE" = ios || "$TEST_TYPE" = osx ]; then
    bash <(curl -s https://codecov.io/bash)
  fi
