branches:
  only:
    - master
language: objective-c
osx_image: xcode6.4
cache: bundler
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
  matrix:
    - TEST_TYPE=ios
    - TEST_TYPE=osx
    - TEST_TYPE=deployment
    - TEST_TYPE=starters
    - TEST_TYPE=podspecs
before_install:
  - bundle install
script:
  - bundle exec rake test:$TEST_TYPE
